version: "3"
services:
  redis:
    image: redis:6.2.4
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass liboruiLBR9911
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      retries: 12
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/redis:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"


